twig:
    file_name_pattern: "*.twig"
    globals:
        app_name: "%env(APP_NAME)%"
    form_themes:
         - 'form/bootstrap_5_custom.html.twig'

when@test:
    twig:
        strict_variables: true
