framework:
  messenger:
    transports:
      sync: 'sync://'
    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
      # You can also route other notifications synchronously during dev if needed:
      # Symfony\Component\Notifier\Message\ChatMessage: sync
      # Symfony\Component\Notifier\Message\SmsMessage: sync
